# Generated by Django 4.2.2 on 2023-06-19 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='stored_url',
            new_name='st_url',
        ),
    ]
