# Generated by Django 4.2.2 on 2023-06-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stored_url',
            name='short_url',
            field=models.CharField(default='okay', max_length=15),
            preserve_default=False,
        ),
    ]
