# Generated by Django 4.2.2 on 2023-06-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_stored_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored_url',
            name='short_url',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
