# Generated by Django 4.2.2 on 2023-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_stored_url_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='stored_urlManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='stored_url',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stored_url',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
