# Generated by Django 4.2.2 on 2023-06-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_stored_urlmanager_stored_url_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stored_urlManager',
        ),
    ]
