# Generated by Django 4.2.2 on 2023-06-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0007_alter_stored_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored_url',
            name='url',
            field=models.CharField(max_length=228),
        ),
    ]
