# Generated by Django 4.2.2 on 2023-06-19 11:17

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0008_alter_stored_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored_url',
            name='url',
            field=models.CharField(max_length=228, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
