# Generated by Django 4.2.8 on 2023-12-23 05:57

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0010_alter_stored_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stored_url',
            name='url',
            field=models.CharField(max_length=10000, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
